/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import app.Projeto_GYM;
import app.Util;
import fachada.Fachada;
import java.sql.Date;
import java.util.ArrayList;
import model.Aluno;
import model.Exercicio;
import model.FichaDeTreino;
import model.FichaExercicio;
import model.Instrutor;

/**
 *
 * @author Insinuante
 */
public class AlunosFichaExercicioJFrame extends javax.swing.JFrame {

    private Aluno aluno;
    private Instrutor instrutor;
    private FichaDeTreino ficha;
    private FichaExercicio fichaExer;
    private ArrayList<FichaExercicio> seg = new ArrayList<>();
    private ArrayList<FichaExercicio> ter = new ArrayList<>();
    private ArrayList<FichaExercicio> qua = new ArrayList<>();
    private ArrayList<FichaExercicio> qui = new ArrayList<>();
    private ArrayList<FichaExercicio> sex = new ArrayList<>();
    private ArrayList<FichaExercicio> sab = new ArrayList<>();
    private ArrayList<FichaExercicio> dom = new ArrayList<>();
    private String obj, obs;
    
    
    public AlunosFichaExercicioJFrame(Aluno aluno) {
        this.aluno = aluno;
        ficha = new FichaDeTreino();
        fichaExer = new FichaExercicio();
        ficha.setExercicios(new ArrayList<>());
        
        initComponents();
         jTextFieldNomeProf.setText(Fachada.getInstance().getByFuncionario_IdInstrutor(Fachada.getFuncionarioLogado().getId()).getFuncionario().getNome());
        preencherComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBack = new javax.swing.JPanel();
        jPanelBlue = new javax.swing.JPanel();
        jLabeAlunos = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTabbedPaneAvaliacao = new javax.swing.JTabbedPane();
        jPanelDetalhes = new javax.swing.JPanel();
        jLabePresq = new javax.swing.JLabel();
        jLabeDataInicio = new javax.swing.JLabel();
        jLabeDataReav = new javax.swing.JLabel();
        jLabeProfessor = new javax.swing.JLabel();
        jLabeObservações = new javax.swing.JLabel();
        jLabeObejetivo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jFormattedTextFieldDataIni = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataReav = new javax.swing.JFormattedTextField();
        jTextFieldNomeProf = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPaneTreino = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonIncluir12 = new javax.swing.JButton();
        domjCheckBox10 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        sabjCheckBox10 = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        sexjCheckBox10 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        quijCheckBox10 = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        quajCheckBox10 = new javax.swing.JCheckBox();
        terjCheckBox10 = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        segjCheckBox10 = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldRepeticoe12 = new javax.swing.JTextField();
        jLabeRepeticoes12 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jSpinnerSerie12 = new javax.swing.JSpinner();
        jLabeSerie12 = new javax.swing.JLabel();
        jComboExercicio = new javax.swing.JComboBox<>();
        jLabeOrdem24 = new javax.swing.JLabel();
        jSpinnerOrdem12 = new javax.swing.JSpinner();
        jLabeOrdem25 = new javax.swing.JLabel();
        jLabeExercicio12 = new javax.swing.JLabel();
        jComboBoxTipoExerc = new javax.swing.JComboBox<>();
        jLabelProcurar1 = new javax.swing.JLabel();
        jButtonImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar avaliação física");
        setExtendedState(6);

        jPanelBack.setBackground(new java.awt.Color(255, 255, 255));

        jPanelBlue.setBackground(new java.awt.Color(45, 118, 232));

        jLabeAlunos.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabeAlunos.setForeground(new java.awt.Color(255, 255, 255));
        jLabeAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Inspection_50px.png"))); // NOI18N
        jLabeAlunos.setText(" Ficha Treino");

        javax.swing.GroupLayout jPanelBlueLayout = new javax.swing.GroupLayout(jPanelBlue);
        jPanelBlue.setLayout(jPanelBlueLayout);
        jPanelBlueLayout.setHorizontalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBlueLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabeAlunos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBlueLayout.setVerticalGroup(
            jPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBlueLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabeAlunos)
                .addGap(28, 28, 28))
        );

        jButtonSalvar.setBackground(new java.awt.Color(45, 118, 232));
        jButtonSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(45, 118, 232));
        jButtonCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jPanelDetalhes.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDetalhes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabePresq.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabePresq.setForeground(new java.awt.Color(45, 118, 232));
        jLabePresq.setText("Prescrição nº");

        jLabeDataInicio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeDataInicio.setForeground(new java.awt.Color(45, 118, 232));
        jLabeDataInicio.setText("Data início");

        jLabeDataReav.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeDataReav.setForeground(new java.awt.Color(45, 118, 232));
        jLabeDataReav.setText("Data reavaliação");

        jLabeProfessor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeProfessor.setForeground(new java.awt.Color(45, 118, 232));
        jLabeProfessor.setText("Professor/Avaliador");

        jLabeObservações.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeObservações.setForeground(new java.awt.Color(45, 118, 232));
        jLabeObservações.setText("Observações");

        jLabeObejetivo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeObejetivo.setForeground(new java.awt.Color(45, 118, 232));
        jLabeObejetivo.setText("Obejetivo");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldDataIni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataIni.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        try {
            jFormattedTextFieldDataReav.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataReav.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jTextFieldNomeProf.setEditable(false);
        jTextFieldNomeProf.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanelDetalhesLayout = new javax.swing.GroupLayout(jPanelDetalhes);
        jPanelDetalhes.setLayout(jPanelDetalhesLayout);
        jPanelDetalhesLayout.setHorizontalGroup(
            jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetalhesLayout.createSequentialGroup()
                .addContainerGap(298, Short.MAX_VALUE)
                .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabeProfessor)
                    .addComponent(jLabeObservações)
                    .addComponent(jLabeObejetivo)
                    .addGroup(jPanelDetalhesLayout.createSequentialGroup()
                        .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabePresq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeDataInicio)
                            .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldDataReav, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabeDataReav)))
                    .addComponent(jTextFieldNomeProf)
                    .addComponent(jTextField3)
                    .addComponent(jScrollPane1))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jPanelDetalhesLayout.setVerticalGroup(
            jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetalhesLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabePresq)
                    .addComponent(jLabeDataInicio)
                    .addComponent(jLabeDataReav))
                .addGap(12, 12, 12)
                .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataReav, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabeProfessor)
                .addGap(12, 12, 12)
                .addComponent(jTextFieldNomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabeObejetivo)
                .addGap(12, 12, 12)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabeObservações)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPaneAvaliacao.addTab("Detalhes", jPanelDetalhes);

        jPaneTreino.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ordem", "Exercício", "Série", "Repetições", "Obs."
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButtonIncluir12.setBackground(new java.awt.Color(45, 118, 232));
        jButtonIncluir12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonIncluir12.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIncluir12.setText("Incluir exercício");
        jButtonIncluir12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluir12ActionPerformed(evt);
            }
        });

        domjCheckBox10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(45, 118, 232));
        jLabel23.setText("Dom");

        sabjCheckBox10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(45, 118, 232));
        jLabel24.setText("Sab");

        sexjCheckBox10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(45, 118, 232));
        jLabel25.setText("Sex");

        quijCheckBox10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(45, 118, 232));
        jLabel26.setText("Qui");

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(45, 118, 232));
        jLabel27.setText("Qua");

        quajCheckBox10.setBackground(new java.awt.Color(255, 255, 255));

        terjCheckBox10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(45, 118, 232));
        jLabel28.setText("Ter");

        jLabel29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(45, 118, 232));
        jLabel29.setText("Seg");

        segjCheckBox10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel30.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(45, 118, 232));
        jLabel30.setText("Ficha:");

        jTextFieldRepeticoe12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldRepeticoe12.setText("10");
        jTextFieldRepeticoe12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRepeticoe12ActionPerformed(evt);
            }
        });

        jLabeRepeticoes12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeRepeticoes12.setForeground(new java.awt.Color(45, 118, 232));
        jLabeRepeticoes12.setText("Repetições");

        jTextField16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });

        jSpinnerSerie12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinnerSerie12.setValue(3);

        jLabeSerie12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeSerie12.setForeground(new java.awt.Color(45, 118, 232));
        jLabeSerie12.setText("Série");

        jComboExercicio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboExercicioActionPerformed(evt);
            }
        });

        jLabeOrdem24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeOrdem24.setForeground(new java.awt.Color(45, 118, 232));
        jLabeOrdem24.setText("Obs.:");

        jSpinnerOrdem12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinnerOrdem12.setValue(1);

        jLabeOrdem25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeOrdem25.setForeground(new java.awt.Color(45, 118, 232));
        jLabeOrdem25.setText("Ordem");

        jLabeExercicio12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabeExercicio12.setForeground(new java.awt.Color(45, 118, 232));
        jLabeExercicio12.setText("Exercício");

        jComboBoxTipoExerc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboBoxTipoExerc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abdome", "Aeróbico", "Antebraço", "Bíceps", "Costas", "Glúteo", "Ombro", "Peito", "Perna", "Tríceps" }));
        jComboBoxTipoExerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoExercActionPerformed(evt);
            }
        });

        jLabelProcurar1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelProcurar1.setForeground(new java.awt.Color(45, 118, 232));
        jLabelProcurar1.setText("Tipo do exercício");

        javax.swing.GroupLayout jPaneTreinoLayout = new javax.swing.GroupLayout(jPaneTreino);
        jPaneTreino.setLayout(jPaneTreinoLayout);
        jPaneTreinoLayout.setHorizontalGroup(
            jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneTreinoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProcurar1)
                    .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(jPaneTreinoLayout.createSequentialGroup()
                            .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSpinnerOrdem12)
                                    .addComponent(jLabeOrdem25))
                                .addComponent(jLabeOrdem24))
                            .addGap(20, 20, 20)
                            .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPaneTreinoLayout.createSequentialGroup()
                                    .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneTreinoLayout.createSequentialGroup()
                                            .addComponent(jLabeExercicio12)
                                            .addGap(311, 311, 311))
                                        .addGroup(jPaneTreinoLayout.createSequentialGroup()
                                            .addComponent(jComboExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)))
                                    .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabeSerie12)
                                        .addComponent(jSpinnerSerie12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabeRepeticoes12)
                                        .addComponent(jTextFieldRepeticoe12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(49, 49, 49)
                            .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel30)
                                .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonIncluir12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPaneTreinoLayout.createSequentialGroup()
                                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel29)
                                            .addComponent(segjCheckBox10))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28)
                                            .addComponent(terjCheckBox10))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel27)
                                            .addComponent(quajCheckBox10))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel26)
                                            .addComponent(quijCheckBox10))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel25)
                                            .addComponent(sexjCheckBox10))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addComponent(sabjCheckBox10))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(domjCheckBox10)
                                            .addComponent(jLabel23)))))))
                    .addComponent(jComboBoxTipoExerc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPaneTreinoLayout.setVerticalGroup(
            jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneTreinoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelProcurar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxTipoExerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPaneTreinoLayout.createSequentialGroup()
                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeOrdem25)
                            .addComponent(jLabeExercicio12)
                            .addComponent(jLabeSerie12)
                            .addComponent(jLabeRepeticoes12))
                        .addGap(18, 18, 18)
                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerOrdem12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerSerie12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRepeticoe12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeOrdem24)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPaneTreinoLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(jPaneTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(segjCheckBox10)
                            .addComponent(terjCheckBox10)
                            .addComponent(quajCheckBox10)
                            .addComponent(sexjCheckBox10)
                            .addComponent(quijCheckBox10)
                            .addComponent(domjCheckBox10)
                            .addComponent(sabjCheckBox10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButtonIncluir12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneAvaliacao.addTab("Treino", jPaneTreino);

        jButtonImprimir.setBackground(new java.awt.Color(45, 118, 232));
        jButtonImprimir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonImprimir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.setToolTipText("Salvar");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackLayout = new javax.swing.GroupLayout(jPanelBack);
        jPanelBack.setLayout(jPanelBackLayout);
        jPanelBackLayout.setHorizontalGroup(
            jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPaneAvaliacao, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanelBackLayout.setVerticalGroup(
            jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackLayout.createSequentialGroup()
                .addComponent(jPanelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPaneAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1010, 726));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Projeto_GYM.fachada.cadastrarFichaDeTreino(getFicha());
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jButtonIncluir12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluir12ActionPerformed
        miniGet();            
    }//GEN-LAST:event_jButtonIncluir12ActionPerformed

    private void jTextFieldRepeticoe12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRepeticoe12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRepeticoe12ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jComboExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboExercicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboExercicioActionPerformed

    private void jComboBoxTipoExercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoExercActionPerformed
        preencherComboBox();
    }//GEN-LAST:event_jComboBoxTipoExercActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox domjCheckBox10;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonIncluir12;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxTipoExerc;
    private javax.swing.JComboBox<String> jComboExercicio;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataIni;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataReav;
    private javax.swing.JLabel jLabeAlunos;
    private javax.swing.JLabel jLabeDataInicio;
    private javax.swing.JLabel jLabeDataReav;
    private javax.swing.JLabel jLabeExercicio12;
    private javax.swing.JLabel jLabeObejetivo;
    private javax.swing.JLabel jLabeObservações;
    private javax.swing.JLabel jLabeOrdem24;
    private javax.swing.JLabel jLabeOrdem25;
    private javax.swing.JLabel jLabePresq;
    private javax.swing.JLabel jLabeProfessor;
    private javax.swing.JLabel jLabeRepeticoes12;
    private javax.swing.JLabel jLabeSerie12;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabelProcurar1;
    private javax.swing.JPanel jPaneTreino;
    private javax.swing.JPanel jPanelBack;
    private javax.swing.JPanel jPanelBlue;
    private javax.swing.JPanel jPanelDetalhes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerOrdem12;
    private javax.swing.JSpinner jSpinnerSerie12;
    private javax.swing.JTabbedPane jTabbedPaneAvaliacao;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldNomeProf;
    private javax.swing.JTextField jTextFieldRepeticoe12;
    private javax.swing.JCheckBox quajCheckBox10;
    private javax.swing.JCheckBox quijCheckBox10;
    private javax.swing.JCheckBox sabjCheckBox10;
    private javax.swing.JCheckBox segjCheckBox10;
    private javax.swing.JCheckBox sexjCheckBox10;
    private javax.swing.JCheckBox terjCheckBox10;
    // End of variables declaration//GEN-END:variables

    public FichaDeTreino getFicha(){

        Date date = Util.getDate(jFormattedTextFieldDataIni.getText());
        Date dateRea = Util.getDate(jFormattedTextFieldDataReav.getText());

        ficha.setData(date);
        ficha.setDataReavaliacao(dateRea);    
        ficha.setInstrutor(Fachada.getInstance().getByFuncionario_IdInstrutor(
                Fachada.getFuncionarioLogado().getId()));
        ficha.setAluno(aluno);
        ficha.setObg(jTextField3.getText());
        ficha.setObs(jTextArea1.getText());
        
        for(FichaExercicio e : seg){
            e.setDia("segunda");
            ficha.getExercicios().add(e);
        }
        for(FichaExercicio e : ter){
            e.setDia("terça");
            ficha.getExercicios().add(e);
        }for(FichaExercicio e : qua){
            e.setDia("quarta");
            ficha.getExercicios().add(e);
        }
        for(FichaExercicio e : qui){
            e.setDia("quinta");
            ficha.getExercicios().add(e);
        }
        for(FichaExercicio e : sex){
            e.setDia("sexta");
            ficha.getExercicios().add(e);
        }
        for(FichaExercicio e : sab){
            e.setDia("sabado");
            ficha.getExercicios().add(e);
        }
        for(FichaExercicio e : dom){
            e.setDia("domingo");
            ficha.getExercicios().add(e);
        }

        seg.clear();
        ter.clear();
        qua.clear();
        qui.clear();
        sex.clear();
        sab.clear();
        dom.clear();  
        
        return ficha;
    }
    
    public FichaExercicio miniGet(){
        fichaExer.setRepeticoes(Integer.parseInt(jTextFieldRepeticoe12.getText()));
        fichaExer.setOrdem(Integer.parseInt(jSpinnerOrdem12.getValue().toString()));
        fichaExer.setSerie(Integer.parseInt(jSpinnerSerie12.getValue().toString()));
        fichaExer.setExercicio(Fachada.getInstance().getExercicioNomeExercicio(jComboExercicio.getSelectedItem() + ""));
        fichaExer.setObs(jTextField16.getText());

        if(segjCheckBox10.isSelected()){
            seg.add(fichaExer);
        }

        if(terjCheckBox10.isSelected()){
            ter.add(fichaExer);
        }

        if(quajCheckBox10.isSelected()){
            qua.add(fichaExer);
        }

        if(quijCheckBox10.isSelected()){
            qui.add(fichaExer);
        }

        if(sexjCheckBox10.isSelected()){
            sex.add(fichaExer);
        }

        if(sabjCheckBox10.isSelected()){
            sab.add(fichaExer);
        }

        if(domjCheckBox10.isSelected()){
            dom.add(fichaExer);
        }

        return fichaExer;
    }
    
        private void preencherComboBox(){
        ArrayList<Exercicio> e = Projeto_GYM.fachada.getAllTipoExercicio(jComboBoxTipoExerc.getSelectedItem()+"");
        if(e!=null){
            jComboExercicio.removeAllItems();
            for(Exercicio ex : e){
                jComboExercicio.addItem(ex.getNome());
            }
        }
    }

}